<?php

namespace autoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * carburantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carburantRepository extends EntityRepository
{
}
