<?php

namespace autoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVenteRepository extends EntityRepository
{
}
