login:
    resource: "@loginBundle/Controller/"
    type:     annotation
    prefix:   /

auto:
    resource: "@autoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
