<?php

namespace loginBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * droitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class droitsRepository extends EntityRepository
{
}
